import type {Metadata} from "next";
import "./globals.css";
import Header from "@/components/Header";
import React from "react";
import Providers from "@/context/Providers";
import AddContent from "@/components/AddContent";
// import {Bebas_Neue} from 'next/font/google';

// const bebasNeue = Bebas_Neue({
//     weight: '400',
//     subsets: ['latin'],
//     display: 'swap',
//     variable: '--font-bn',
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    // const classWithBebasFont = bebasNeue.variable;
    return (
        <html lang="en">
        <body className="bg-brandGray">
        <Providers>
            <Header/>
            {children}
        </Providers>
        </body>
        </html>
    )
}
